mklink /D "%USERPROFILE%\vimfiles" "myconfig\.vim"
mklink /D "%USERPROFILE%\.vim" "myconfig\.vim"
mklink "%USERPROFILE%\.vimrc" "myconfig\.vimrc"
mklink "%USERPROFILE%\.vimrc.full" "myconfig\.vimrc.full"
mklink "%USERPROFILE%\.gvimrc" "myconfig\.gvimrc"
